# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: images.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'images.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimages.proto\x12\x06images\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"2\n\x11ImageListResponse\x12\x1d\n\x06images\x18\x01 \x03(\x0b\x32\r.images.Image2O\n\rImagesService\x12>\n\tGetImages\x12\x16.google.protobuf.Empty\x1a\x19.images.ImageListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'images_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=53
  _globals['_IMAGE']._serialized_end=106
  _globals['_IMAGELISTRESPONSE']._serialized_start=108
  _globals['_IMAGELISTRESPONSE']._serialized_end=158
  _globals['_IMAGESSERVICE']._serialized_start=160
  _globals['_IMAGESSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
